Portfolio project Setup1
hydaline-code/Portfolio_Project pull request #1
Opened 2023-02-15 16:46 UTC by hydaline-code

Hello great coders. Please her you will find the first part of the portfolio_setup project, I implemented what was required us here please  kindly do a review so thanks.

2023-02-15 18:02 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @hydaline-code , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional job but still, there are some changes that need to be addressed to go to the next level 💯 

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 18:02 UTC, ABDULALI3468 commented on index.html
> +    <object data="./svgfiles/image_1.svg" type="image/svg+xml" ></object>
Please consider adding a (`a` tag) to your logo.
    - This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-02-15 18:02 UTC, ABDULALI3468 commented on index.html
> +    <object class="menuimg" data="./svgfiles/ic_menu.svg" type="image/svg+xml" ></object>
Please consider adding a  `nav` tag to your HAMBURGER icon.
    - The `nav` tag is for semantics reasons, and the right position for convention and user experience for mobile devices.

2023-02-15 18:02 UTC, ABDULALI3468 commented on index.html
> +  </header>
Currently, your design is not matching exactly to the Figma template you have used. There is a difference in Logo style and margin around it. I am attaching a comparison image so you can understand it well.

## Figma Design:-

![image](https://user-images.githubusercontent.com/94223367/219111730-942efbc8-f5c1-46a5-8e2e-550d47f44af7.png)

## Your Design:-

![image](https://user-images.githubusercontent.com/94223367/219111781-6ccd1afd-c6de-452a-8df3-2f30635c0fb6.png)

2023-02-15 18:02 UTC, ABDULALI3468 commented on index.html
> +  </div>
The section needs to have a proper background image (decorations are always background images, not `img` tags).
    - If an image is not part of the content (aesthetic reasons) use a CSS background image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

In short, you need to use the CSS property of background image for it instead of the HTML tag. Also, could you consider matching it to the design by making it 100 percent of the viewport without any margins around it?

2023-02-15 18:02 UTC, ABDULALI3468 commented on index.html
> +    </button>
Please consider adding the CSS states of hover and pressed on the button as follows it will make your project look more professional and its a project requirement also to make it exactly like the template:-

![image](https://user-images.githubusercontent.com/94223367/219113526-6242be34-2dff-497c-980e-1853a11b21ce.png)

2023-02-16 09:10 UTC, hydaline-code commented on index.html
> +  </div>
Thanks for the suggestion but i tried implementing it but to no avail.

2023-02-16 09:36 UTC, Abenezer-Tilahun commented on index.html
> +    <object data="./svgfiles/image_1.svg" type="image/svg+xml" ></object>
Fixed.

2023-02-16 09:37 UTC, Abenezer-Tilahun commented on index.html
> +    <object class="menuimg" data="./svgfiles/ic_menu.svg" type="image/svg+xml" ></object>
Fixed.

2023-02-16 09:41 UTC, Abenezer-Tilahun commented on index.html
> +  </header>
Fixed.

2023-02-16 09:42 UTC, Abenezer-Tilahun commented on index.html
> +    </button>
Fixed,

2023-02-16 09:43 UTC, Abenezer-Tilahun commented on index.html
> +  </div>
Fixed.

2023-02-16 09:44 UTC, Abenezer-Tilahun approved these changes
Hi @hydaline-code 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git Hub -Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 06:41 UTC, merged