Mobile menu
hydaline-code/Portfolio_Project pull request #9
Opened 2023-03-07 16:14 UTC by hydaline-code

🙌 Hello hope everything is okay, in this part of my work, you will find the hamburger menu done with javascript for its interactivity. The corresponding linter checks for CSS and javascript is okay kindly appreciate by giving it a review for improvement .thanks

2023-03-07 16:26 UTC, GzimAsani requested changes
### Hello, @hydaline-code                    :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your styling, it is almost the same  :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 16:26 UTC, GzimAsani commented on index.js
> +}
- [ ] When I click one of the items on the menu I get redirected correctly, but then the X is present and not the hamburger menu. Kindly fix this 
https://www.awesomescreenshot.com/video/15393281?key=9d6fa7e058bdccd9568869407f132248

2023-03-07 16:26 UTC, GzimAsani commented on index.js
> +}
- [ ] The menu should extend all the way down and when opened you should be able to see only the menu, also please work on design to make it more similar 

Yours:

![image](https://user-images.githubusercontent.com/62705947/223484603-3470c97e-6125-4510-8990-49b0f99aadc3.png)

Design:
![image](https://user-images.githubusercontent.com/62705947/223484754-672fdd44-9f63-4e2c-966b-978bdbef8b4b.png)

2023-03-08 08:32 UTC, wayungi approved these changes
Hi @hydaline-code , 
![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 13:46 UTC, merged